[tasks.test]
command = "cargo"
args = ["test", "${@}", "--", "--nocapture", "--color=always"]

[tasks.test-leak]
condition = { channels = [
    "nightly",
], fail_message = "needs to be run with nightly rust." }
# env = { "RUSTFLAGS" = "-C link-arg=-fuse-ld=mold -Z sanitizer=leak"  } # causes SIGSEGV
env = { "RUSTFLAGS" = "-Z sanitizer=leak" }
command = "cargo"
args = ["test", "${@}", "--", "--nocapture", "--color=always"]

[config]
reduce_output = false # print fail_message
