[tasks.test]
command = "cargo"
args = ["test", "${@}", "--", "--nocapture", "--color=always"]

[tasks.mold-test]
command = "mold"
args = ["-run", "cargo", "test", "${@}", "--", "--nocapture", "--color=always"]

[tasks.mold-test-leak]
condition = { channels = [
    "nightly",
], fail_message = "needs to be run with nigtly rust." }
env = { "RUSTFLAGS" = "-Z sanitizer=leak" }
command = "mold"
args = ["-run", "cargo", "test", "${@}", "--", "--nocapture", "--color=always"]

[tasks.test-leak]
condition = { channels = [
    "nightly",
], fail_message = "needs to be run with nightly rust." }
env = { "RUSTFLAGS" = "-Z sanitizer=leak" }
command = "cargo"
args = ["test", "${@}", "--", "--nocapture", "--color=always"]

[config]
reduce_output = false # print fail_message
